services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - /Users/nvdittakavi/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: unless-stopped

# This block is what you are missing!
volumes:
  prometheus-data:
